
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Colegio
{

using System;
    using System.Collections.Generic;
    
public partial class CALIFICACION
{

    public int IdCalificacion { get; set; }

    public Nullable<int> IdCurricula { get; set; }

    public Nullable<int> IdAlumno { get; set; }

    public Nullable<double> Nota { get; set; }

    public Nullable<bool> Activo { get; set; }

    public Nullable<System.DateTime> FechaRegistro { get; set; }

    public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }

    public string Usu_Ult_Mod { get; set; }



    public virtual ALUMNO ALUMNO { get; set; }

    public virtual CURRICULA CURRICULA { get; set; }

}

}
