
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Colegio
{

using System;
    using System.Collections.Generic;
    
public partial class CURRICULA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CURRICULA()
    {

        this.CALIFICACION = new HashSet<CALIFICACION>();

    }


    public int IdCurricula { get; set; }

    public Nullable<int> IdDocenteNivelDetalleCurso { get; set; }

    public string Descripcion { get; set; }

    public Nullable<bool> Activo { get; set; }

    public Nullable<System.DateTime> FechaRegistro { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CALIFICACION> CALIFICACION { get; set; }

    public virtual DOCENTE_NIVELDETALLE_CURSO DOCENTE_NIVELDETALLE_CURSO { get; set; }

}

}
