
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Colegio
{

using System;
    using System.Collections.Generic;
    
public partial class DOCENTE_NIVELDETALLE_CURSO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DOCENTE_NIVELDETALLE_CURSO()
    {

        this.CURRICULA = new HashSet<CURRICULA>();

    }


    public int IdDocenteNivelDetalleCurso { get; set; }

    public Nullable<int> IdNivelDetalleCurso { get; set; }

    public Nullable<int> IdDocente { get; set; }

    public Nullable<bool> Activo { get; set; }

    public Nullable<System.DateTime> FechaRegistro { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CURRICULA> CURRICULA { get; set; }

    public virtual DOCENTE DOCENTE { get; set; }

    public virtual NIVEL_DETALLE_CURSO NIVEL_DETALLE_CURSO { get; set; }

}

}
