
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Colegio
{

using System;
    using System.Collections.Generic;
    
public partial class HORARIO
{

    public int IdHorario { get; set; }

    public Nullable<int> IdNivelDetalleCurso { get; set; }

    public string DiaSemana { get; set; }

    public Nullable<System.TimeSpan> HoraInicio { get; set; }

    public Nullable<System.TimeSpan> HoraFin { get; set; }

    public Nullable<bool> Activo { get; set; }

    public Nullable<System.DateTime> FechaRegistro { get; set; }



    public virtual NIVEL_DETALLE_CURSO NIVEL_DETALLE_CURSO { get; set; }

}

}
