
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Colegio
{

using System;
    using System.Collections.Generic;
    
public partial class MATRICULA
{

    public int IdMatricula { get; set; }

    public Nullable<int> ValorCodigo { get; set; }

    public string Codigo { get; set; }

    public string Situacion { get; set; }

    public Nullable<int> IdAlumno { get; set; }

    public Nullable<int> IdNivelDetalle { get; set; }

    public Nullable<int> IdApoderado { get; set; }

    public string InstitucionProcedencia { get; set; }

    public Nullable<bool> EsRepitente { get; set; }

    public Nullable<bool> Activo { get; set; }

    public Nullable<System.DateTime> FechaRegistro { get; set; }



    public virtual ALUMNO ALUMNO { get; set; }

    public virtual APODERADO APODERADO { get; set; }

    public virtual NIVEL_DETALLE NIVEL_DETALLE { get; set; }

}

}
