
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Colegio
{

using System;
    using System.Collections.Generic;
    
public partial class NIVEL_DETALLE
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NIVEL_DETALLE()
    {

        this.MATRICULA = new HashSet<MATRICULA>();

        this.NIVEL_DETALLE_CURSO = new HashSet<NIVEL_DETALLE_CURSO>();

    }


    public int IdNivelDetalle { get; set; }

    public Nullable<int> IdNivel { get; set; }

    public Nullable<int> IdGradoSeccion { get; set; }

    public Nullable<int> TotalVacantes { get; set; }

    public Nullable<int> VacantesDisponibles { get; set; }

    public Nullable<int> VacantesOcupadas { get; set; }

    public Nullable<bool> Activo { get; set; }

    public Nullable<System.DateTime> FechaRegistro { get; set; }



    public virtual GRADO_SECCION GRADO_SECCION { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MATRICULA> MATRICULA { get; set; }

    public virtual NIVEL NIVEL { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NIVEL_DETALLE_CURSO> NIVEL_DETALLE_CURSO { get; set; }

}

}
